#+title: Nodejs
* Node js and Javascript
:PROPERTIES:
:ID:       6c94391a-b52c-4308-93bc-d770b29857fc
:END:
** Typescript
:PROPERTIES:
:ID:       2291a412-ed3a-4b26-a489-ab11deafee44
:END:
For basic documentation on typescript see the [[https://www.typescriptlang.org/docs/handbook/2/basic-types.html][Documentation]]
*** Compilation
Compilation of files can be done in any of the following ways:

- ~tsc~ to compile the nearby project (recognized via [[id:da390266-7df1-4692-80eb-e19a3df1c11e][tsconfig]].
- ~tsc somfile.ts~ compile a single file
- ~tsc --project othertsconfig.json~
- ~tsc index.js --declaration --emitDeclarationOnly~
- ~tsc src/*.ts~ compile all .ts files in ~src~ folder.
- ~tsc one.ts two.ts --target esnext --outFile index.js~ combine two files
*** Config file
:PROPERTIES:
:ID:       da390266-7df1-4692-80eb-e19a3df1c11e
:END:
Typescript is configured with ~tsconfig.json~

Same as ~package.json~ for typescript. Specifies options for Typescript compilation.

**** Useful properties
- ~target~ will specify to which features in your code will get downgraded. For example ~${temlate} string~ might be downgraded to string concatenation. Using ~es6~ is a strong choice, but all depends.
- ~module~ - which module type is generated? (CommonJs, ES modules, etc...)
- ~noImplicitAny~ - will throw an error in all places where type is ~any~ or is implicitly made ~any~.
- ~strictNullChecks~ - helps to handle ~null~ and ~undefined~, especially in cases where a value was not initialized and still used
*** Add typescript to webpack
-  Install ~ts-loader~
-  Add a rule to your ~webpack.config.js~

#+begin_src js
rules: [
    {
        test: /.tsx?$/,
        use: [
            {
                loader: 'ts-loader', options: { transpileOnly: true }
            }
        ]
    }
]
#+end_src

You might want to add this to your ~webpack.config.js~ as well:

#+begin_src js
module.exports {
    // ...
    entry: //...
    // ...
    resolve: {
        extensions: ['.ts', '.js'],
    },
    // ...
}
#+end_src
*** Resources
Resources on typescript:
- Documentation: [[https://www.typescriptlang.org/docs/handbook/intro.html]]
*** Classes
Classes documentation can be found [[https://www.typescriptlang.org/docs/handbook/2/classes.html][here]]
*** Functions
**** Call signature
:PROPERTIES:
:ID:       b27f6b66-2d4c-4746-8b5b-1829d6b70b31
:END:
If you want to have a callable object type with some properties in [Typescript](https://andreid049.github.io/no-brainer//#Typescript), you need a `call sugnature`

#+begin_src js
type CallableWithProps = {
    property: string;
    (name: string): void;
}

function doSomething(fn: CallableWithProps) {
   console.log(fn.property);
   fn("test");
}
#+end_src

#+RESULTS:
**** Constructor signature
In [[id:2291a412-ed3a-4b26-a489-ab11deafee44][Typescript]] you can declare constructor functions (the ones you can call with `new`) like below.

#+begin_src js
type Example = {
    new (prop: string): SomeObject;
}
#+end_src

You can also combine it with [[id:b27f6b66-2d4c-4746-8b5b-1829d6b70b31][Call signature]]
** Add eslint to project
- Install eslint – ~npm i -D eslint~
- Run – ~npx eslint --init~
- Choose appropriate steps in the wizard
** Jest
:PROPERTIES:
:ID:       4e8cb1ee-18bb-478d-85be-62a166b71cd0
:END:
Popular testing framework in JavaScript and node.

Examples and docs: [[https://jestjs.io/][https://jestjs.io/]]
*** Add jest to a project (with babel)
1.  Install [[id:4e8cb1ee-18bb-478d-85be-62a166b71cd0][Jest]] with ~npm i -D jest~
2.  If you wish to use Babel, for example you want typescript - ~npm i -D babel-jest @babel/core @babel/preset-env~ and add to ~babel.config.js~:

#+begin_src js
module.exports = {
  presets: [['@babel/preset-env', {targets: {node: 'current'}}]],
};
#+end_src
*** Add typescript to jest
If you want to add typescript support, ~npm i --D @babel/preset-typescript @types/jest~

Then add ~@babel/preset-typescript~ to the list of presets in your ~babel.config.js~.

#+begin_src js
module.exports = {
  presets: [
    ['@babel/preset-env', {targets: {node: 'current'}}],
    '@babel/preset-typescript', // <-- this
  ],
};
#+end_src
** Add prettier to project
*** Install

~npm i -D prettier~

*** Config file

#+begin_src js
// prettier.config.js or .prettierrc.js
module.exports = {
  trailingComma: "es5",
  tabWidth: 4,
  semi: true,
  singleQuote: true,
};
#+end_src
** Webpack
:PROPERTIES:
:ID:       30de9951-46cc-45cc-8d74-98d53664569b
:END:
Webpack is a code bundler
*** Add Webpack to a project
To add [[id:30de9951-46cc-45cc-8d74-98d53664569b][Webpack]] to your project:

1.  ~npm i -D webpack webpack-cli [webpack-dev-server]~
2.  Create a ~webpack.config.js~

#+begin_src js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    mode: 'development',
    entry: __dirname + '/index.ts',
    output: {
        path: __dirname + '/dist',
        filename: 'index.js',
        publicPath: '/'
    },
    resolve: {
        extensions: ['.ts', '.js'],
    },
    module: {
        rules: [ ]
    },
    // this plugin is necessary if you want your bundle to be added to a html while developing
    plugins: [
        new HtmlWebpackPlugin({
            template: __dirname + '/public/index.html',
            inject: 'body',
            publicPath: __dirname + '/public'
        })
    ],
}
#+end_src
*** Creating a umd library using webpack
To create a library that exposes a variable like jquery, using Webpack, but also is available as a common js module:

In your js/ts file, export the necessary functions:
#+begin_src js
export default function a(text) {
    console.log(text);
}
#+end_src

In your config file:
#+begin_src js
module.exports = {
  mode: // ...,
    // ...
  output: {
        // ...
    globalObject: 'this', // <-- this is needed so library can be required as a commonjs module
    library: {
      name: 'myLibraryName', // <-- this variable will be exposed by your bundle
      type: 'umd',
    },
  },
#+end_src

Then you can include it in your html:
#+begin_src html
<script src="https://example.org/path/to/mybundle.js"></script>
<script>
  myLibraryName.a('webpack');
</script>
#+end_src

Or js:
#+begin_src js
const myLib = require('myLibrary');
#+end_src

See:
- [[https://webpack.js.org/configuration/output/#outputlibrary]]
- [[https://webpack.js.org/guides/author-libraries/]]
- [[https://webpack.js.org/configuration/output/#outputglobalobject]]

** Common js modules
Common js modules are the modules using require function. This is the native mechanism used in [[id:6c94391a-b52c-4308-93bc-d770b29857fc][Node js]]. (at least it was before Es modules appeared). Each file is considered a module. Objects like require, module and others are available thanks to Module wrapping.
*** Module wrapping
Before a commonjs module is executed, it's contents are wrapped in a function. It looks approximatively like this:

#+begin_src js
(function(exports, require, module, __filename, __dirname) {
 /* Module contents */
});
#+end_src

This helps encapsulation, and provides useful local variables:

-   ~exports~: alias for ~module.exports~
-   ~require~: function for requiring other modules. Require returns the common js module's ~exports~ object.
-   ~module~: reference to the current module
-   ~__filename~ and ~__dirname~: representing current filename and directory name
*** The ~.mjs~ extension
It is not possible to ~require()~ files that have the ~.mjs~ extension. Attempting to do so will throw an error. The .mjs extension is reserved for ~Es modules~ which cannot be loaded via ~require()~.
*** Module resolution
If exact file name is not found. Node.js will attempt to find a file with ~.js~, ~.json~, or ~.node~ extensions.

Also, depending on path prefix:
- ~/~ means path to the module is absolute
- ~./~, ~../~ etc. means path to the module is relative
- if there is no prefix, it's either a core module (ex: path), or it will be looked up in node_modules folder If none of above work, ~require~ will throw a ~MODULE_NOT_FOUND~ exception.

In order for Node js to be able to recognize a folder as a module, it should meet any of below criteria:
- Folder should have a `package.json` with a `main` field in it. In below case, `require('./my-module')` will load and run `./my-module/lib/my-module.js`
#+begin_src js
{
  "name": "my-module",
  "main: "./lib/my-module.js"
}
#+end_src

- In case no ~package.json~ is found, Node.js will look for ~index.js~ or ~index.node~ files.
** Common js cycle
Sometimes common js modules depend on one another. In this case, an object might receive a dependency that was not loaded completely. For example:

~a.js~:
#+begin_src js
console.log('a starting');
exports.done = false;
const b = require('./b.js');
console.log('in a, b.done = %j', b.done);
exports.done = true;
console.log('a done');
#+end_src

~b.js~:
#+begin_src js
console.log('b starting');
exports.done = false;
const a = require('./a.js');
console.log('in b, a.done = %j', a.done);
exports.done = true;
console.log('b done');
#+end_src

~main.js~:
#+begin_src js
console.log('main starting');
const a = require('./a.js');
const b = require('./b.js');
console.log('in main, a.done = %j, b.done = %j', a.done, b.done);
#+end_src

The output of above will be:
#+begin_src text
main starting
a starting
b starting
in b, a.done=false
b done
in a, b.done=true
a done
in main, a.done = true, b.done = true
#+end_src
** Conditional import
:PROPERTIES:
:ID:       76f572b9-74d7-469e-a37b-320c03dbd319
:END:
In package.json, it is possible to define aliases for imports, and apply them conditionally depending on environment that is being run, or how the package is imported (with ~require~ or ~import~)

#+begin_src js
...
"imports": {
  "#parser": {
    "import": "./src/parser.mjs",
    "require": "./src/parser.cjs",
    "node": "node-parser", // should always come after import or require
    "default:": "./src/parser-not-found.js" // should always come last
  }
}
...
#+end_src

Usage:
#+begin_src js
// if used from node, 'node parser will be imported'
import default from '#parser';

// if not used from node, and imported, will look for ./src/parser.mjs
import default from '#parser';

// if required, will look for ./src/parser.cjs
const { default } = require('#parser');

// in any other cases, wil load ./src/parser-not-found.js
#+end_src

- **Note**: that the imported entry must start with ~#~ in order to avoid conflicts with Bare specifiers (see [[id:e0d4bd08-3ac8-45f8-80cf-8c97fd2fbdea][Import specifiers]])
** Conditional export
Example, different files are loaded if package is ~import'ed~ or ~require'd~: Same rules as in [[id:76f572b9-74d7-469e-a37b-320c03dbd319][Conditional import]]

#+begin_src js
// ./node_modules/pkg/package.json
{
  "type": "module",
  "main": "./index.cjs",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  }
}
#+end_src

** Import specifiers
:PROPERTIES:
:ID:       e0d4bd08-3ac8-45f8-80cf-8c97fd2fbdea
:END:
Import specifiers represent the strings that can be used within Es modules (after ~from~ keywork in ~import~ statement), or with ~import()~ in [[id:dd393aee-ef6c-4800-9d92-0d332f8cc4ff][Dynamic import]]

There are 3 types of import specifiers:
1. Relative specifiers - like ~./some-package/index.js~
2. Bare specifier - like ~fs~ or ~axios~
3. Absolute specifiers - like ~file:///opt/file/example.js~
** Dynamic import
:PROPERTIES:
:ID:       dd393aee-ef6c-4800-9d92-0d332f8cc4ff
:END:
Normally, with Static import, code of the loaded packages is evaluated at load time. Dynamic import is a mechanism useful when you want to import something conditionally, and evaluate the code at run time, like:

#+begin_src js
if (somethingIsTrue) {
 import('./some-package/index.js').then((package) =>
  /* do something */);
} else {
 import('./some-other-package/index.js').then((package) =>
 /* do something else */);
}
#+end_src

It is used by calling ~import~ as a function and providing. It returns a ~Promise~ containing the imported package. Also, you can ~await~ a dynamic import with a top level await (Experimental). Using dynamic imports, you can use es modules from CommonJs modules modules or vice versa.

**WARNING**: using Dynamic import disables such useful features as Tree shaking done by static analyzers. Use it wisely.
** Data attributes
Data attributes are special type of html attributes:

#+begin_src html
<a data-open="true" href="...">...
#+end_src

From js, this attribute can be accessed by using ~.getAttribute()~ specifying the full name ~data-open~. But there is a more convenient way: using the ~dataset~ property. You could access it like this ~el.dataset.open~.
